name: Mirror to Bitbucket
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.BITBUCKET_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H bitbucket.org >> ~/.ssh/known_hosts
      - name: Push
        run: |
          git remote add bitbucket git@bitbucket.org:damoyri/subscription.git
          git push --force --all bitbucket
          git push --force --tags bitbucket
